---
title: "Alyssa - Graphs"
format: html
editor: visual
---

```{r}
#| label: load-pkgs
#| message: false
#| warning: false

library(tidyverse)
```

## Dataset

```{r}
#| label: load-data
#| message: false

breed_traits <- read_csv("data/breed_traits.csv") %>%
  select(-Breed)
trait_description <- read_csv("data/trait_description.csv")
breed_rank_all <- read_csv("data/breed_rank.csv")

breed_full <- cbind(breed_rank_all, breed_traits)
```

```{r}
lollipop_data <- breed_full %>%
  filter((`2020 Rank` > 0 & `2020 Rank` <= 10) | (`2020 Rank` > 185 & `2020 Rank` <= 195)) %>%
  select(-`2013 Rank`, -`2014 Rank`, -`2015 Rank`, -`2016 Rank`, -`2017 Rank`, -`2018 Rank`, -`2019 Rank`) %>%
  mutate(popularity = case_when(`2020 Rank` <= 10 ~ "Popular", 
                                `2020 Rank` >= 186 ~ "Unpopular")) %>%
  select(-`2020 Rank`, -links, -Image, -`Coat Type`, -`Coat Length`) %>%
  pivot_longer(is.numeric, names_to = "Trait", values_to = "Score") %>%
  group_by(popularity, Trait) %>%
  summarize(`Mean Score` = mean(Score), 
            `SD Score` = sd(Score), 
            `Median Score` = median(Score), 
            `Max Score` = max(Score), 
            `Min Score` = min(Score))
```

```{r}
ggplot(lollipop_data, mapping = aes(x = `Mean Score`, y = Trait, color = popularity)) +
  geom_errorbarh(aes(xmin = 0, xmax = `Mean Score`),
                   height = 0,
                   position = position_dodge(width = .5)) +
  geom_point(position = position_dodge(width = .5)) +
  geom_errorbar(aes(xmin = (`Mean Score` - `SD Score`), xmax = (`Mean Score` + `SD Score`)),
                position = position_dodge(width = .5)) 
```

```{r}
colors <- c("Unpopular" = "#E97451", "Popular" = "#8ABD91")

lollipop_data %>%
  pivot_wider(names_from = popularity, values_from = contains("Score")) %>%
  ggplot(., mapping = aes(y = Trait)) +
  geom_segment(aes(x = `Mean Score_Unpopular`, xend = `Mean Score_Popular`, y = Trait, yend = Trait), color = "darkgrey") +
  geom_point(aes(x = `Mean Score_Unpopular`, y = Trait, color = "Unpopular")) +
  geom_point(aes(x = `Mean Score_Popular`, y = Trait, color = "Popular")) +
  scale_color_manual(values = colors) +
  labs(title = "Average Breed Trait Scores for Popular and Unpopular Dogs", 
       subtitle = "Based on 2020 Popularity Rankings", 
       y = "Breed Trait",
       x = "Average Score",
       color = "Popularity") +
  theme_minimal()

lollipop_data %>%
  pivot_wider(names_from = popularity, values_from = contains("Score")) %>%
  ggplot(., mapping = aes(y = Trait)) +
  geom_segment(aes(x = `Mean Score_Unpopular`, xend = `Mean Score_Popular`, y = Trait, yend = Trait), color = "darkgrey") +
  geom_point(aes(x = `Mean Score_Unpopular`, y = Trait, color = "Unpopular")) +
  geom_point(aes(x = `Mean Score_Popular`, y = Trait, color = "Popular")) +
  labs(title = "Average Breed Trait Scores for Popular and Unpopular Dogs", 
       subtitle = "Based on 2020 Popularity Rankings", 
       y = "Breed Trait",
       x = "Average Score",
       color = "Popularity") +
  theme_minimal() +
  geom_errorbar(aes(xmin = (`Mean Score_Unpopular` - `SD Score_Unpopular`), xmax = (`Mean Score_Unpopular` + `SD Score_Unpopular`), color = "Unpopular"), alpha = 0.4) +
  geom_errorbar(aes(xmin = (`Mean Score_Popular` - `SD Score_Popular`), xmax = (`Mean Score_Popular` + `SD Score_Popular`), color = "Popular"), alpha = 0.4) +
  scale_color_manual(values = colors)
```
```{r}
lollipop_data %>%
  pivot_wider(names_from = popularity, values_from = contains("Score")) %>%
  mutate(score_diff = `Mean Score_Popular` - `Mean Score_Unpopular`) %>%
  select(Trait, score_diff) %>%
  arrange(desc(score_diff))

lollipop_data %>%
  pivot_wider(names_from = popularity, values_from = contains("Score")) %>%
  mutate(Trait = factor(Trait, levels = c("Trainability Level", "Playfulness Level", "Openness To Strangers", "Drooling Level", "Watchdog/Protective Nature", "Adaptability Level", "Mental Stimulation Needs", "Affectionate With Family", "Coat Grooming Frequency", "Good With Young Children", "Shedding Level", "Energy Level", "Good With Other Dogs", "Barking Level")), 
         Trait = fct_rev(Trait)) %>%
  ggplot(., mapping = aes(y = Trait)) +
  geom_segment(aes(x = `Mean Score_Unpopular`, xend = `Mean Score_Popular`, y = Trait, yend = Trait), color = "darkgrey") +
  geom_point(aes(x = `Mean Score_Unpopular`, y = Trait, color = "Unpopular")) +
  geom_point(aes(x = `Mean Score_Popular`, y = Trait, color = "Popular")) +
  scale_color_manual(values = colors) +
  labs(title = "Average Breed Trait Scores for Popular and Unpopular Dogs", 
       subtitle = "Based on 2020 Popularity Rankings, Ordered by Difference Between Popular and Unpopular Dogs", 
       y = "Breed Trait",
       x = "Average Score",
       color = "Popularity") +
  theme_minimal()
```





